In [1]:
import numpy as np

In [2]:
x_1 = np.array([2,5,450])
x_1

array([  2,   5, 450])

In [3]:
x_2 = np.array([3,6,950])

In [4]:
features = ['people', 'rooms', 'sq feet']

In [6]:
data = np.array([x_1,x_2])
data

array([[  2,   5, 450],
       [  3,   6, 950]])

In [8]:
import pandas as pd
pd.DataFrame(data,columns=features)

people  rooms  sq feet
0       2      5      450
1       3      6      950

In [16]:
feature_4 = np.array([1,2])

In [19]:
#updated_data = np.array([data,feature_4])
updated_data = np.c_[data,feature_4]
updated_data

array([[  2,   5, 450,   1],
       [  3,   6, 950,   2]])

In [15]:
bias_array = np.ones((2, 1))
bias_array

array([[1.],
       [1.]])

In [14]:
data_with_bias = np.c_[bias_array, data]
data_with_bias

array([[  1.,   2.,   5., 450.],
       [  1.,   3.,   6., 950.]])

In [22]:
x_1, x_2

(array([  2,   5, 450]), array([  3,   6, 950]))

In [26]:
np.c_[x_1, x_2]

array([[  2,   3],
       [  5,   6],
       [450, 950]])

In [28]:
np.c_[[x_1] ,[x_2]]

array([[  2,   5, 450,   3,   6, 950]])

In [21]:
np.c_[np.array([[1,2,3]]), np.array([[4,5,6]])]

array([[1, 2, 3, 4, 5, 6]])